name: Get Book-My-Show Pipeline logs

on:
  push:
    branches:
      - "master"
      - "task/**"
  pull_request:
    branches:
      - "master"
      - "task/**"

# The error occurs because the `id-token: write` permission is not enabled in the workflow.
# This permission is required for OIDC-based authentication when using the `Azure/login` action.
# Generally we face this error when we are using the `Azure/login` action in our workflow for deploying an application in AKS
permissions:
  id-token: write
  contents: read

jobs:
# Build & Push docker image to Docker Hub
  docker_build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get Book-My-Show Pipeline logs
        run: |
          ls -la
          python3 get_pipeline_logs.py kcm-org-dev-1 Book-My-Show ${{ secrets.PAT }}

